<a href="https://colab.research.google.com/github/hirajya/CCMACLRL_EXAM_COM222/blob/main/Midterm_IntroToML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Midterm Examination
Introduction to Machine Learning

### Import Libraries

In [972]:
import numpy as np
from scipy import stats
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

### Data Preprocessing

In [973]:
# Import Data

dataset_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/train.csv?raw=true'
df = pd.read_csv(dataset_url)

test_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/test.csv?raw=true'
dt=pd.read_csv(test_url)

sample_submission_url = 'https://github.com/robitussin/CCMACLRL_EXAM/blob/a46a4e2a001dedaefc9b431d480b508ce86c2d96/datasets/sample_submission.csv?raw=true'
sf=pd.read_csv(sample_submission_url)

In [974]:
# Data Shape

print(f"Train Dataset Dimension: {df.shape}")
print(f"Test Dataset Dimension: {dt.shape}")

Train Dataset Dimension: (188533, 13)
Test Dataset Dimension: (125690, 12)

In [975]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [976]:
df.describe()

                  id     model_year         milage         price
count  188533.000000  188533.000000  188533.000000  1.885330e+05
mean    94266.000000    2015.829998   65705.295174  4.387802e+04
std     54424.933488       5.660967   49798.158076  7.881952e+04
min         0.000000    1974.000000     100.000000  2.000000e+03
25%     47133.000000    2013.000000   24115.000000  1.700000e+04
50%     94266.000000    2017.000000   57785.000000  3.082500e+04
75%    141399.000000    2020.000000   95400.000000  4.990000e+04
max    188532.000000    2024.000000  405000.000000  2.954083e+06

In [977]:
df.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [978]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [979]:
df.describe(include='all')

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
count,188533.000000,188533,188533,188533.000000,188533.000000,183450,188533,188533,188533,188533,186081,167114,1.885330e+05
unique,NaN,57,1897,NaN,NaN,7,1117,52,319,156,2,1,NaN
top,NaN,Ford,F-150 XLT,NaN,NaN,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,NaN
freq,NaN,23088,2945,NaN,NaN,165940,3462,49904,48658,107674,144514,167114,NaN
mean,94266.000000,NaN,NaN,2015.829998,65705.295174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.387802e+04
std,54424.933488,NaN,NaN,5.660967,49798.158076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.881952e+04
min,0.000000,NaN,NaN,1974.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+03
25%,47133.000000,NaN,NaN,2013.000000,24115.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000e+04
50%,94266.000000,NaN,NaN,2017.000000,57785.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.082500e+04
75%,141399.000000,NaN,NaN,2020.000000,95400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.990000e+04
max,188532.000000,NaN,NaN,2024.000000,405000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.954083e+06

#### Check Duplicated Rows

In [980]:
# check duplicated rows

duplicated_rows_cnt = df.duplicated().sum()
print(f"Number of duplicated rows: {duplicated_rows_cnt}")

Number of duplicated rows: 0

In [981]:
# Outlier (price) removal

def remove_outliers_percentile(df, column, lower_percentile=0.01, upper_percentile=0.99):
    lower_bound = df[column].quantile(lower_percentile)
    upper_bound = df[column].quantile(upper_percentile)
    filtered_df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

    return filtered_df

# Function to remove outliers using Z-score
def remove_outliers_zscore(df, column, z_thresh=3):
    z_scores = np.abs(stats.zscore(df[column]))
    filtered_df = df[z_scores < z_thresh]

    return filtered_df

#### Remove Outliers

In [982]:
# Removing outliers

print(f"Number of rows before outlier removal: {df.shape[0]}")
df = remove_outliers_percentile(df, 'price', lower_percentile=0.01, upper_percentile=0.99)
print(f"Number of rows after outlier removal: {df.shape[0]}")
df = remove_outliers_zscore(df, 'price', z_thresh=3)
print(f"Number of rows after outlier removal: {df.shape[0]}")

Number of rows before outlier removal: 188533
Number of rows after outlier removal: 185132
Number of rows after outlier removal: 180981

In [983]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

#### Check Null Count

In [984]:
df.isnull().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        4909
engine              0
transmission        0
ext_col             0
int_col             0
accident         2324
clean_title     19917
price               0
dtype: int64

#### Fill NA using most freq

In [985]:
# Fill missing values for categorical columns
imputer = SimpleImputer(strategy='most_frequent')
df['fuel_type'] = imputer.fit_transform(df[['fuel_type']]).ravel()
df['accident'] = imputer.fit_transform(df[['accident']]).ravel()
df['clean_title'] = imputer.fit_transform(df[['clean_title']]).ravel()

In [986]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [987]:
df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

#### lowercase all values

In [988]:
# prompt: give me a code that will lowercase all the values

# Iterate through each column and convert string values to lowercase
for column in df.columns:
    if df[column].dtype == object:  # Check if the column contains string values
        df[column] = df[column].str.lower()

df.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,mini,cooper s base,2007,213000,gasoline,172.0hp 1.6l 4 cylinder engine gasoline fuel,a/t,yellow,gray,none reported,yes,4200
1,1,lincoln,ls v8,2002,143250,gasoline,252.0hp 3.9l 8 cylinder engine gasoline fuel,a/t,silver,beige,at least 1 accident or damage reported,yes,4999
2,2,chevrolet,silverado 2500 lt,2002,136731,e85 flex fuel,320.0hp 5.3l 8 cylinder engine flex fuel capab...,a/t,blue,gray,none reported,yes,13900
3,3,genesis,g90 5.0 ultimate,2017,19500,gasoline,420.0hp 5.0l 8 cylinder engine gasoline fuel,transmission w/dual shift mode,black,black,none reported,yes,45000
4,4,mercedes-benz,metris base,2021,7388,gasoline,208.0hp 2.0l 4 cylinder engine gasoline fuel,7-speed a/t,black,beige,none reported,yes,97500

#### Normalizing Data Color

In [989]:
df['int_col'].value_counts() #exception

int_col
black           103837
beige            23685
gray             20498
brown             5595
red               4849
                 ...
classic red          6
nougat brown         6
bianco polar         5
cobalt blue          3
beluga               3
Name: count, Length: 152, dtype: int64

#### Transforming to Dummies / One hot encoding

In [990]:
le = LabelEncoder()

for col in ['brand', 'model', 'engine', 'ext_col', 'int_col', 'transmission']:
  df[col] = le.fit_transform(df[col])

df = pd.get_dummies(df, columns=['fuel_type', 'accident', 'clean_title'],
                         prefix=['fuel_type', 'accident', 'clean_title'])

In [991]:
df.head()

,id,brand,model,model_year,milage,engine,transmission,ext_col,int_col,price,fuel_type_diesel,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_–,accident_at least 1 accident or damage reported,accident_none reported,clean_title_yes
0,0,37,460,2007,213000,116,37,313,69,4200,False,False,True,False,False,False,False,False,True,True
1,1,28,961,2002,143250,366,37,264,8,4999,False,False,True,False,False,False,False,True,False,True
2,2,9,1556,2002,136731,640,37,36,69,13900,False,True,False,False,False,False,False,False,True,True
3,3,15,761,2017,19500,863,48,26,12,45000,False,False,True,False,False,False,False,False,True,True
4,4,35,1063,2021,7388,259,23,26,8,97500,False,False,True,False,False,False,False,False,True,True

In [992]:
df.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'engine',
       'transmission', 'ext_col', 'int_col', 'price', 'fuel_type_diesel',
       'fuel_type_e85 flex fuel', 'fuel_type_gasoline', 'fuel_type_hybrid',
       'fuel_type_not supported', 'fuel_type_plug-in hybrid', 'fuel_type_–',
       'accident_at least 1 accident or damage reported',
       'accident_none reported', 'clean_title_yes'],
      dtype='object')

#### Transforming true and false to 0-1

In [993]:
for column in df.columns:
  if pd.api.types.is_bool_dtype(df[column]):
    df[column] = df[column].astype(int)

In [994]:
df.head()

,id,brand,model,model_year,milage,engine,transmission,ext_col,int_col,price,fuel_type_diesel,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_–,accident_at least 1 accident or damage reported,accident_none reported,clean_title_yes
0,0,37,460,2007,213000,116,37,313,69,4200,0,0,1,0,0,0,0,0,1,1
1,1,28,961,2002,143250,366,37,264,8,4999,0,0,1,0,0,0,0,1,0,1
2,2,9,1556,2002,136731,640,37,36,69,13900,0,1,0,0,0,0,0,0,1,1
3,3,15,761,2017,19500,863,48,26,12,45000,0,0,1,0,0,0,0,0,1,1
4,4,35,1063,2021,7388,259,23,26,8,97500,0,0,1,0,0,0,0,0,1,1

# Scalling Data - MinMaxScaler

In [995]:
# from sklearn.preprocessing import MinMaxScaler

# numeric_cols = ['brand', 'model', 'model_year', 'milage', 'engine', 'transmission', 'ext_col', 'int_col']

# scaler = MinMaxScaler()

# df_scaled = df.copy()
# df_scaled[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# df_scaled.head()

### dtest cleaned

In [996]:
# Fill missing values for categorical columns
imputer = SimpleImputer(strategy='most_frequent')
dt['fuel_type'] = imputer.fit_transform(dt[['fuel_type']]).ravel()
dt['accident'] = imputer.fit_transform(dt[['accident']]).ravel()
dt['clean_title'] = imputer.fit_transform(dt[['clean_title']]).ravel()

for column in dt.columns:
    if dt[column].dtype == object:
        dt[column] = dt[column].str.lower()

le1 = LabelEncoder()

for col in ['brand', 'model', 'engine', 'ext_col', 'int_col', 'transmission', 'clean_title']:
  dt[col] = le1.fit_transform(dt[col])

dt = pd.get_dummies(dt, columns=['fuel_type', 'accident', 'clean_title'],
                         prefix=['fuel_type', 'accident', 'clean_title'])

for column in dt.columns:
  if pd.api.types.is_bool_dtype(dt[column]):
    dt[column] = dt[column].astype(int)

    from sklearn.preprocessing import MinMaxScaler

numeric_cols = ['brand', 'model', 'model_year', 'milage', 'engine', 'transmission', 'ext_col', 'int_col']
dt.drop(columns=['int_col', 'ext_col'], axis=1, inplace=True)
# scaler = MinMaxScaler()

# dt_scaled = dt.copy()
# dt_scaled[numeric_cols] = scaler.fit_transform(dt[numeric_cols])

# dt_scaled.head()

In [997]:
df.shape

(180981, 20)

In [998]:
dt.shape

(125690, 17)

In [999]:
df.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'engine',
       'transmission', 'ext_col', 'int_col', 'price', 'fuel_type_diesel',
       'fuel_type_e85 flex fuel', 'fuel_type_gasoline', 'fuel_type_hybrid',
       'fuel_type_not supported', 'fuel_type_plug-in hybrid', 'fuel_type_–',
       'accident_at least 1 accident or damage reported',
       'accident_none reported', 'clean_title_yes'],
      dtype='object')

In [1000]:
dt.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'engine',
       'transmission', 'fuel_type_diesel', 'fuel_type_e85 flex fuel',
       'fuel_type_gasoline', 'fuel_type_hybrid', 'fuel_type_not supported',
       'fuel_type_plug-in hybrid', 'fuel_type_–',
       'accident_at least 1 accident or damage reported',
       'accident_none reported', 'clean_title_0'],
      dtype='object')

### Training Model

In [1001]:
# # prompt: give me train test split

# from sklearn.model_selection import train_test_split
# X = df_scaled.drop('price', axis=1)
# y = df_scaled['price']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [1002]:
# prompt: give me train test split

from sklearn.model_selection import train_test_split
X = df.drop(columns=['price', 'ext_col', 'int_col', 'clean_title_yes'], axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [1003]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180981 entries, 0 to 188532
Data columns (total 16 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   id                                               180981 non-null  int64
 1   brand                                            180981 non-null  int64
 2   model                                            180981 non-null  int64
 3   model_year                                       180981 non-null  int64
 4   milage                                           180981 non-null  int64
 5   engine                                           180981 non-null  int64
 6   transmission                                     180981 non-null  int64
 7   fuel_type_diesel                                 180981 non-null  int64
 8   fuel_type_e85 flex fuel                          180981 non-null  int64
 9   fuel_type_gasoline                               180981 non-null  int64
 10  fuel_type_hybrid                                 180981 non-null  int64
 11  fuel_type_not supported                          180981 non-null  int64
 12  fuel_type_plug-in hybrid                         180981 non-null  int64
 13  fuel_type_–                                      180981 non-null  int64
 14  accident_at least 1 accident or damage reported  180981 non-null  int64
 15  accident_none reported                           180981 non-null  int64
dtypes: int64(16)
memory usage: 23.5 MB

In [1004]:
y.info()

<class 'pandas.core.series.Series'>
Index: 180981 entries, 0 to 188532
Series name: price
Non-Null Count   Dtype
--------------   -----
180981 non-null  int64
dtypes: int64(1)
memory usage: 2.8 MB

In [1005]:
import numpy as np
from sklearn.metrics import mean_squared_error

# Model fitting and predictions
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Applying transformation (log in this case)
y_pred_transformed = np.log(y_pred)

# Outputs
print("Predictions (Transformed):", y_pred_transformed)
print("R-squared:", model.score(X, y))
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

# Calculating RMSE (note: comparing against the transformed y_test if necessary)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE:", rmse)

Predictions (Transformed): [10.88340315 10.71082131 11.0132996  ...         nan 11.05164929
 10.71133293]
R-squared: 0.48564677721275684
Coefficients: [ 2.18491227e-04  5.56392085e+01 -2.23596796e-01  1.15530945e+03
 -1.76279329e-01  2.22404255e+01  1.71962233e+01  5.07039721e+03
 -1.63628515e+03 -9.21529224e+01  2.95388715e+03  1.40588257e+03
 -2.06194200e+03 -5.63978686e+03 -1.56071236e+03  1.56071236e+03]
Intercept: -2297229.9553408753
RMSE: 18008.397707355245

In [1006]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144784 entries, 2021 to 127098
Data columns (total 16 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   id                                               144784 non-null  int64
 1   brand                                            144784 non-null  int64
 2   model                                            144784 non-null  int64
 3   model_year                                       144784 non-null  int64
 4   milage                                           144784 non-null  int64
 5   engine                                           144784 non-null  int64
 6   transmission                                     144784 non-null  int64
 7   fuel_type_diesel                                 144784 non-null  int64
 8   fuel_type_e85 flex fuel                          144784 non-null  int64
 9   fuel_type_gasoline                               144784 non-null  int64
 10  fuel_type_hybrid                                 144784 non-null  int64
 11  fuel_type_not supported                          144784 non-null  int64
 12  fuel_type_plug-in hybrid                         144784 non-null  int64
 13  fuel_type_–                                      144784 non-null  int64
 14  accident_at least 1 accident or damage reported  144784 non-null  int64
 15  accident_none reported                           144784 non-null  int64
dtypes: int64(16)
memory usage: 18.8 MB

In [1007]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36197 entries, 124989 to 44188
Data columns (total 16 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   id                                               36197 non-null  int64
 1   brand                                            36197 non-null  int64
 2   model                                            36197 non-null  int64
 3   model_year                                       36197 non-null  int64
 4   milage                                           36197 non-null  int64
 5   engine                                           36197 non-null  int64
 6   transmission                                     36197 non-null  int64
 7   fuel_type_diesel                                 36197 non-null  int64
 8   fuel_type_e85 flex fuel                          36197 non-null  int64
 9   fuel_type_gasoline                               36197 non-null  int64
 10  fuel_type_hybrid                                 36197 non-null  int64
 11  fuel_type_not supported                          36197 non-null  int64
 12  fuel_type_plug-in hybrid                         36197 non-null  int64
 13  fuel_type_–                                      36197 non-null  int64
 14  accident_at least 1 accident or damage reported  36197 non-null  int64
 15  accident_none reported                           36197 non-null  int64
dtypes: int64(16)
memory usage: 4.7 MB

In [1008]:
id = sf.pop('id')
dt.drop(columns=['clean_title_0'], axis=1, inplace=True)
y_pred = model.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'class': y_pred
})


# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission_file_r.csv', index=False)
print("Submission file created: submission_file_r.csv")

Submission file created: submission_file_r.csv

In [1009]:
dt

,id,brand,model,model_year,milage,engine,transmission,fuel_type_diesel,fuel_type_e85 flex fuel,fuel_type_gasoline,fuel_type_hybrid,fuel_type_not supported,fuel_type_plug-in hybrid,fuel_type_–,accident_at least 1 accident or damage reported,accident_none reported
0,188533,26,1365,2015,98000,326,16,0,0,1,0,0,0,0,0,1
1,188534,26,1352,2020,9142,787,29,0,0,0,1,0,0,0,0,1
2,188535,14,642,2022,28121,541,3,0,0,1,0,0,0,0,0,1
3,188536,3,182,2016,61258,193,38,0,0,1,0,0,0,0,0,1
4,188537,3,181,2018,59000,365,37,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125685,314218,35,782,2014,83315,732,23,0,0,1,0,0,0,0,0,1
125686,314219,3,1255,2019,29336,511,38,0,0,1,0,0,0,0,0,1
125687,314220,3,184,2012,77634,673,37,0,0,1,0,0,0,0,0,1
125688,314221,3,1251,2012,112000,673,37,0,0,1,0,0,0,0,0,1
125689,314222,9,1649,2018,66840,718,37,0,0,1,0,0,0,0,0,1